### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by KidTechnical** [BlueStaggo/AuthenticAdventure#2]
This is probably a stupid question but how do you install this? It's not like a modern Forge/Fabric mod where you just plop the files in a mods folder, at least as far as I know. Also is this compatible with BetaCraft Launcher?

**Comment by BlueStaggo** [comment]
![image](https://github.com/BlueStaggo/AuthenticAdventure/assets/71090710/019f29b3-8af1-4b20-b839-12e67bee2a13)
