### ISSUE TITLE
OptiFine compatibility

### ISSUE THREAD

**Issue by danielfs0** [BlueStaggo/AuthenticAdventure#22]
It would be nice if OptiFine could be installed along this mod. Right now the game refuses to load if you install OptiFine and Authentic Adventure together.

I assume the lighting fixes of AA interferes with the lighting optimization of OptiFine.

These are the classes in minecraft,jar that conflict between these two mods:

- acq.class
- lr.class
- zq.class
- hu.class
- jy.class
- vl.class
- aaw.class
- l.class
- ct.class

For reference, I'm using OptiFine_1.2.5_HD_A.

**Comment by BlueStaggo** [comment]
Due to complications with OptiFine's licensing, I won't be doing this.
