### ISSUE TITLE
Normal Blocks that cannot be broken

### ISSUE THREAD

**Issue by zmarceline** [BlueStaggo/AuthenticAdventure#3]
While playing the latest release I noticed several times I wasnt able to mine usually mineable blocks, first it was tree logs and leaves then stone too, I tried different tools and my fist but the block wouldnt break just play the break animations but it would never be mined fully. 
it was rare and only certain cases it would happen, I could still mine logs and leaves but every once in a while there was a unbreakable version of those blocks, not certain if its limited to those 3 though.

**Comment by BlueStaggo** [comment]
I think that was to do with an issue with infinite world height which has since been fixed.
