### ISSUE TITLE
Beta lighting not updating with time of day in servers

### ISSUE THREAD

**Issue by holycannoliimmario** [BlueStaggo/AuthenticAdventure#9]
When using Beta lighting instead of Hybrid lighting, nighttime doesn't cause it to get darker outside. While shadows still work, going outside at night looks like fullbright. Doesn't matter whether or not fast-lighting is enabled, and the only difference from the defaults (that I'm aware of) is that the world height is 512.

Examples be upon ye:
![2024-05-14_09 51 28](https://github.com/BlueStaggo/AuthenticAdventure/assets/169814834/a3f840f7-c61c-4eaf-af57-ebb231c4ceff)
![2024-05-14_09 51 37](https://github.com/BlueStaggo/AuthenticAdventure/assets/169814834/31d9b4d7-7f2f-439b-a260-32c87a1cb706)

**Comment by BlueStaggo** [comment]
Fixed in 1.3
